In [ ]:
import numpy as np

**Title: 6CS012 Worksheet 0**


**Name: Kriti Basnet**

# **Exercise on Functions**

**Task 1 — Unit Conversion Program**

In [ ]:
def unit_converter():
    """
    Converts units for length, weight, and volume.

    Parameters:
    None (takes user input)

    Returns:
    float : converted value
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter choice (1/2/3): ")

        value = float(input("Enter the value to convert: "))

        if choice == "1":
            print("1. meters to feet")
            print("2. feet to meters")

            sub = input("Choose option: ")

            if sub == "1":
                result = value * 3.28084
                print("Result:", result, "ft")

            elif sub == "2":
                result = value / 3.28084
                print("Result:", result, "m")

        elif choice == "2":
            print("1. kg to pounds")
            print("2. pounds to kg")

            sub = input("Choose option: ")

            if sub == "1":
                result = value * 2.20462
                print("Result:", result, "lbs")

            elif sub == "2":
                result = value / 2.20462
                print("Result:", result, "kg")

        elif choice == "3":
            print("1. liters to gallons")
            print("2. gallons to liters")

            sub = input("Choose option: ")

            if sub == "1":
                result = value * 0.264172
                print("Result:", result, "gal")

            elif sub == "2":
                result = value / 0.264172
                print("Result:", result, "L")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 2
Enter the value to convert: 3
1. kg to pounds
2. pounds to kg
Choose option: 1
Result: 6.613859999999999 lbs


**Task 2 — Mathematical Operations on List**

In [ ]:
def calculate(numbers, operation):
    if operation == "sum":
        return sum(numbers)
    elif operation == "avg":
        return sum(numbers) / len(numbers)
    elif operation == "max":
        return max(numbers)
    elif operation == "min":
        return min(numbers)

try:
    numbers = [float(x) for x in input("Enter numbers separated by spaces: ").split()]

    operations = {
        "1": "sum",
        "2": "avg",
        "3": "max",
        "4": "min"
    }

    print("\nSelect operation")
    print("1 - Sum")
    print("2 - Average")
    print("3 - Maximum")
    print("4 - Minimum")

    choice = input("Enter choice: ")

    if choice in operations:
        result = calculate(numbers, operations[choice])
        print("Result:", result)
    else:
        print("Invalid choice")

except ValueError:
    print("Please enter valid numbers.")
except ZeroDivisionError:
    print("Cannot calculate average of empty list.")

Enter numbers separated by spaces: 4

Select operation
1 - Sum
2 - Average
3 - Maximum
4 - Minimum
Enter choice: 3
Result: 4.0


# **Exercise on List Manipulation:**

**1 Extract every other element**

In [ ]:
def extract_every_other(lst):
    result = []
    for i in range(0, len(lst), 2):
        result.append(lst[i])
    return result

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


**2 Get sublist**

In [1]:
def get_sublist(lst, start, end):
    """Returns sublist from start to end index inclusive."""
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


**3 Reverse list**

In [ ]:
def reverse_list(lst):
    return list(reversed(lst))

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


**4 Remove first and last**

In [ ]:
def remove_first_last(lst):
    """Removes first and last element."""
    lst.pop(0)
    lst.pop(-1)
    return lst

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


**5 Get first n**

In [ ]:
def get_first_n(lst, n):
    result = []
    for i in range(n):
        result.append(lst[i])
    return result

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


**6 Get last n**

In [ ]:
def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


**7 Reverse skip**

In [ ]:
def reverse_skip(lst):
    result = []
    for i in range(len(lst)-2, -1, -2):
        result.append(lst[i])
    return result

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


# **Exercise on Nested List:**

**1 Flatten list**

In [ ]:
def flatten(lst):
    return [item for sub in lst for item in sub]

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


**2 Access nested element**

In [ ]:
from functools import reduce

def access_nested_element(lst, indices):
    return reduce(lambda x, y: x[y], indices, lst)

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst, [1,2]))

6


**3 Sum nested**

In [ ]:
def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


**4 Remove element**

In [ ]:
def remove_element(lst, elem):
    return [remove_element(i, elem) if isinstance(i, list) else i
            for i in lst if i != elem]

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


**5 Find max**

In [ ]:
def find_max(lst):
    """Finds maximum in nested list."""
    maximum = float('-inf')
    for item in lst:
        if isinstance(item,list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum,item)
    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


**6 Count occurrences**

In [ ]:
def count_occurrences(lst, elem):
    return sum(count_occurrences(i, elem) if isinstance(i, list) else (i == elem) for i in lst)

print(count_occurrences([[1,2],[2,3],[2,4]], 2))

3


**7 Deep flatten**

In [ ]:
def deep_flatten(lst):
    if not lst:
        return []
    if isinstance(lst[0], list):
        return deep_flatten(lst[0]) + deep_flatten(lst[1:])
    return [lst[0]] + deep_flatten(lst[1:])

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


**8 Nested average**

In [ ]:
def average_nested(lst):
    """Returns average of nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


# **To-Do – NumPy**

**Problem 1 — Array Creation**

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr1 = np.zeros((2,2))  # Using zeros instead of empty
print("Empty-like array (zeros used):\n", arr1)

# 2. Initialize an all ones array with size 4x2
arr2 = np.full((4,2), 1)  # Using full instead of ones
print("\nOnes array (via full):\n", arr2)

# 3. Array filled with specific value
arr3 = np.ones((3,3)) * 7  # Multiply ones by 7
print("\nFull array (via ones * 7):\n", arr3)

# 4. Zeros array like another array
arr4 = np.empty_like(arr2) * 0  # Using empty_like and multiplying by 0
print("\nZeros like array (via empty_like*0):\n", arr4)

# 5. Ones array like another array
arr5 = np.full_like(arr1, 1)  # Using full_like
print("\nOnes like array (via full_like):\n", arr5)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]  # <-- Define the list first
arr6 = np.asarray(new_list)  # Using asarray instead of array
print("\nArray from list (via asarray):\n", arr6)

Empty-like array (zeros used):
 [[0. 0.]
 [0. 0.]]

Ones array (via full):
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]

Full array (via ones * 7):
 [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]

Zeros like array (via empty_like*0):
 [[0 0]
 [0 0]
 [0 0]
 [0 0]]

Ones like array (via full_like):
 [[1. 1.]
 [1. 1.]]

Array from list (via asarray):
 [1 2 3 4]


**Problem 2 — Array Manipulation**

In [ ]:
import numpy as np

# 1. Array from 10 to 49
arr = np.arange(10, 50)
print("10 to 49:\n", arr)

# Alternative: using np.linspace
arr_alt = np.linspace(10, 49, 40, dtype=int)
print("\n10 to 49 (alternative):\n", arr_alt)

# 2. 3x3 matrix from 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", matrix)

# Alternative: using np.arange + reshape with a different syntax
matrix_alt = np.arange(0, 9).reshape(3, 3)
print("\n3x3 Matrix (alternative):\n", matrix_alt)

# 3. Identity matrix
identity = np.eye(3)
print("\nIdentity Matrix:\n", identity)

# Alternative: using np.identity
identity_alt = np.identity(3)
print("\nIdentity Matrix (alternative):\n", identity_alt)

# 4. Random array of size 30 and mean
rand_arr = np.random.rand(30)
print("\nRandom Array Mean:", rand_arr.mean())

# Alternative: using np.random.uniform
rand_arr_alt = np.random.uniform(0, 1, 30)
print("Random Array Mean (alternative):", rand_arr_alt.mean())

# 5. 10x10 random array with min and max
rand_matrix = np.random.rand(10, 10)
print("\nMinimum:", rand_matrix.min())
print("Maximum:", rand_matrix.max())

# Alternative: using np.random.uniform
rand_matrix_alt = np.random.uniform(size=(10,10))
print("Minimum (alternative):", rand_matrix_alt.min())
print("Maximum (alternative):", rand_matrix_alt.max())

# 6. Zero array size 10 and replace 5th element
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\nZero array with 5th element replaced:\n", zero_arr)

# Alternative: using np.put
zero_arr_alt = np.zeros(10)
np.put(zero_arr_alt, 4, 1)
print("\nZero array with 5th element replaced (alternative):\n", zero_arr_alt)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed array:\n", arr[::-1])

# Alternative: using np.flip
arr_alt = np.flip(arr)
print("Reversed array (alternative):\n", arr_alt)

# 8. 2D array with border 1 and inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\nBorder array:\n", border)

# Alternative: using np.pad
inner = np.zeros((3,3))
border_alt = np.pad(inner, pad_width=1, constant_values=1)
print("Border array (alternative):\n", border_alt)

# 9. Checkerboard pattern
checker = np.zeros((8,8))
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print("\nCheckerboard pattern:\n", checker)

# Alternative: using np.indices and sum modulo 2
checker_alt = (np.indices((8,8)).sum(axis=0) % 2)
print("Checkerboard pattern (alternative):\n", checker_alt)

10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

10 to 49 (alternative):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Matrix (alternative):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity Matrix (alternative):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array Mean: 0.356559284664089
Random Array Mean (alternative): 0.5345340668816726

Minimum: 0.03602700651045776
Maximum: 0.9606895308334676
Minimum (alternative): 0.0020516668205859956
Maximum (alternative): 0.9965884629285476

Zero array with 5th element replaced:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Zero array with 5th element replaced (alternative):
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array:
 [0 4 0 0 2 1]
Reversed array (alternative):
 [0 4 0 0 2 1]

Border array:
 [[1. 1.

**Problem 3 — Array Operations**

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Add arrays
print("Addition:\n", x + y)

# 2 Subtract arrays
print("\nSubtraction:\n", x - y)

# 3 Multiply array by integer
print("\nMultiply by 3:\n", x * 3)

# 4 Square each element
print("\nSquare:\n", x**2)

# 5 Dot products
print("\nv dot w:", np.dot(v,w))
print("x dot v:\n", np.dot(x,v))
print("x dot y:\n", np.dot(x,y))

# 6 Concatenate
print("\nConcatenate x and y (rows):\n", np.concatenate((x,y),axis=0))

print("\nConcatenate v and w (columns):\n",
      np.concatenate((v.reshape(-1,1), w.reshape(-1,1)),axis=1))

# 7 Concatenate x and v
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("\nError:", e)
    print("Explanation: x is 2D array while v is 1D, dimensions do not match.")

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

v dot w: 219
x dot v:
 [29 77]
x dot y:
 [[19 22]
 [50 58]]

Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (columns):
 [[ 9 11]
 [10 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2D array while v is 1D, dimensions do not match.


**Problem 4 — Matrix Operations**

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
result = A @ A_inv   # using @ instead of np.dot
print("A * A^-1 =\n", result)

# 2. Prove AB ≠ BA
AB = A @ B
BA = B @ A
print("\nAB =\n", AB)
print("\nBA =\n", BA)
print("\nAB == BA? ", np.allclose(AB, BA))  # checks equality numerically

# 3. Prove (AB)^T = B^T A^T
left = (AB).T
right = B.T @ A.T
print("\n(AB)^T =\n", left)
print("\nB^T A^T =\n", right)
print("\nAre they equal? ", np.allclose(left, right))

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

AB == BA?  False

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]

Are they equal?  True


**Solve Linear Equation System**

Equations:2x − 3y + z = −1 ,
x − y + 2z = −3 ,
3x + y − z = 9

In [ ]:
import numpy as np

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Solve using np.linalg.solve
X = np.linalg.solve(A, B)

print("Solution [x y z] =", X)

Solution [x y z] = [ 2.  1. -2.]


**Using NumPy Linear Algebra Function**

In [ ]:
import numpy as np

# Example matrices
A = np.array([[2, 1], [1, 3]])
B = np.array([5, 10])

# Using matrix inverse
solution = np.dot(np.linalg.inv(A), B)

print("Solution using matrix inverse:\n", solution)

Solution using matrix inverse:
 [1. 3.]


In [2]:
import numpy as np
import time

**Element-wise Addition**

In [3]:
size = 10**6

# Python lists
list1 = list(np.random.rand(size))
list2 = list(np.random.rand(size))

start = time.time()

result_list = []
for i in range(size):
    result_list.append(list1[i] + list2[i])

end = time.time()
print("Python List Addition Time:", end - start)

Python List Addition Time: 0.20792317390441895


In [5]:
a = np.random.rand(size)
b = np.random.rand(size)

start = time.time()

result_numpy = a + b

end = time.time()
print("NumPy Addition Time:", end - start)

NumPy Addition Time: 0.007117509841918945


**Element-wise Multiplication**

In [6]:
start = time.time()

result_list = []
for i in range(size):
    result_list.append(list1[i] * list2[i])

end = time.time()
print("Python List Multiplication Time:", end - start)

Python List Multiplication Time: 0.26143646240234375


In [7]:
start = time.time()

result_numpy = a * b

end = time.time()
print("NumPy Multiplication Time:", end - start)

NumPy Multiplication Time: 0.007879018783569336


**Dot Product**

In [8]:
start = time.time()

dot = 0
for i in range(size):
    dot += list1[i] * list2[i]

end = time.time()
print("Python Dot Product Time:", end - start)

Python Dot Product Time: 0.2920830249786377


In [9]:
start = time.time()

dot_numpy = np.dot(a, b)

end = time.time()
print("NumPy Dot Product Time:", end - start)

NumPy Dot Product Time: 0.005562782287597656


**Matrix Multiplication**

In [10]:
n = 50

A = np.random.rand(n,n).tolist()
B = np.random.rand(n,n).tolist()

start = time.time()

result = [[0]*n for _ in range(n)]

for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Python Matrix Multiplication Time:", end - start)

Python Matrix Multiplication Time: 0.0504307746887207


In [11]:
A = np.random.rand(n,n)
B = np.random.rand(n,n)

start = time.time()

result = np.dot(A, B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.006227731704711914


NumPy operations are significantly faster than Python loops because NumPy uses vectorization and optimized C implementations. Python lists rely on explicit loops which are slower. Therefore, for large numerical computations, NumPy provides better performance and efficiency.